server.port=8100
server.forward-headers-strategy=framework
spring.application.name=gateway-service

internal.gateway.service.name=pw-gateway
internal.header.name=pw-service-name
internal.iam.service.name=iam-service
internal.utils.service.name=utils-service

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=DEBUG

end.point.swagger=/v3/api-docs
end.point.auth=/auth
opened.end.points=${end.point.swagger},${end.point.auth}

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.api-docs.enabled=true
springdoc.api-docs.groups.enabled=true
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.defaultModelsExpandDepth=-1

internal.inner.auth.filter=InnerAuthFilter
internal.token.validation.filter=TokenValidationFilter

spring.cloud.gateway.httpclient.connect-timeout=70000
spring.cloud.gateway.httpclient.response-timeout=70s